services:
  - name: frontend
    type: web
    buildCommand: |
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4200

  - name: backend
    type: web
    buildCommand: npm install
    startCommand: npm run server
